### ISSUE TITLE
Error when inserting input with validation from controller

### ISSUE THREAD

**Issue by shlomogoldstein** [ghiscoding/angular-validation#82]
We insert a html via controller into our view (I know it's bad...) like so:

```
// rule in rules...
<td translate="{{rule.id}}" translate-values="rule.parameterInputs"  translate-compile></td>
```

```
// ctrl, for each rule...
// in rule.parameterInputs, we store the input...

          '<input class="form-control form-control-inline"' +
          'ng-model="' + modelName + '"' +
          'name="parameterInput' + parameter.id + '"' +
          'validation="required"' +
          '>'
```

Html output, at runtime
```
<input class="form-control form-control-inline ng-pristine ng-untouched ng-valid ng-scope" ng-model="rules[0].parameters[1].value" name="parameterInput1" validation="required">
```

Produces the error for each input:

```
TypeError: Cannot read property 'getAttribute' of null
    at x (http://localhost:6040/bower_components/angular-validation-ghiscoding/dist/angular-validation.min.js:10:6696)
    at y (http://localhost:6040/bower_components/angular-validation-ghiscoding/dist/angular-validation.min.js:10:5543)
    at new _ (http://localhost:6040/bower_components/angular-validation-ghiscoding/dist/angular-validation.min.js:10:13491)
    at link (http://localhost:6040/bower_components/angular-validation-ghiscoding/dist/angular-validation.min.js:9:3072)
    at invokeLinkFn (http://localhost:6040/bower_components/angular/angular.js:8652:9)
    at nodeLinkFn (http://localhost:6040/bower_components/angular/angular.js:8152:11)
    at compositeLinkFn (http://localhost:6040/bower_components/angular/angular.js:7543:13)
    at publicLinkFn (http://localhost:6040/bower_components/angular/angular.js:7418:30)
    at compile.A (http://localhost:6040/bower_components/angular-translate/angular-translate.min.js:6:17275)
    at http://localhost:6040/bower_components/angular-translate/angular-translate.min.js:6:16950 <input class="form-control form-control-inline ng-pristine ng-untouched ng-valid ng-scope" ng-model="rules[47].parameters[0].value" name="parameterInput78" validation="required">
```

Another question: is it possible disable the input field based error messages below an input field? I only want to use the summary above the form, not the feedback for each input field. Thanks!

**Comment by shlomogoldstein** [comment]
Figured it out, this error comes from not having a form element around the inputs:

<form name="abc">

**Comment by ghiscoding** [comment]
Seen your post and I'm reopening it because I see some benefits here. 
1- I fixed the `getAttribute` of null, so that it doesn't throw an error from my code anymore
2- For the question of disabling error messages below inputs... it's not currently in play but I'm adding it to the Global Options you can set

In both cases, this will be available in the next version coming soon.

**Comment by ghiscoding** [comment]
Added a new Global Options of `hideErrorUnderInputs`, make it True if you just want to use Validation Summary as you mentioned. [Wiki - Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options)

Pushed in latest version [1.4.14](https://github.com/ghiscoding/angular-validation/releases/tag/v1.4.14)

**Comment by shlomogoldstein** [comment]
Thanks for all the changes! Great to have this added. Would it be possible to disable error under one specific input rather disabling it globally? Like silently validating an input without error feedback (summary would give the error message)
